on: [push, pull_request]
name: CI
jobs:
  build:
    runs-on: ubuntu-16.04
    strategy:
      matrix:
        racket-version: [ '7.5' ]
    name: Racket ${{ matrix.racket-version }}
    steps:
      - uses: actions/checkout@master
      - name: Setup Racket
        uses: Bogdanp/setup-racket@v0.5
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}
      - name: Install siek-language-lib
        run: raco pkg install --name siek-language-lib --link --auto --batch siek-language-lib/
      - name: Install siek-language-test
        run: raco pkg install --name siek-language-test --link --auto --batch siek-language-test/
      - name: Test siek-langauge
        run: raco test -c tests/siek-language
      - run: raco pkg install --name siek-interpreter-lib --link --auto --batch siek-interpreter-lib/
      - run: raco pkg install --name siek-interpreter-test --link --auto --batch siek-interpreter-test/
      - run: raco test -c tests/siek-interpreter
      - run: raco pkg install --name siek-compiler-lib --link --auto --batch siek-compiler-lib/
      - run: raco pkg install --name siek-compiler-test --link --auto --batch siek-compiler-test/
      - run: raco test -c tests/siek-compiler
