on: [push, pull_request]

name: CI

jobs:
  build:
    runs-on: ubuntu-16.04

    strategy:
      matrix:
        racket-version: [ '7.5' ]

    name: Racket ${{ matrix.racket-version }}

    steps:
      - uses: actions/checkout@master

      - name: Setup Racket
        uses: Bogdanp/setup-racket@v0.5
        with:
          architecture: x64
          version: ${{ matrix.racket-version }}

      - name: Install siek-language-lib
        run: raco pkg install --name siek-language-lib --link --auto --batch siek-language-lib/

      - name: Install siek-language-test
        run: raco pkg install --name siek-language-test --link --auto --batch siek-language-test/

      - name: Run siek-langauge tests
        run: raco test -c tests/siek-language

      - name: Install siek-interpreter-lib
        run: raco pkg install --name siek-interpreter-lib --link --auto --batch siek-interpreter-lib/

      - name: Install siek-interpreter-test
        run: raco pkg install --name siek-interpreter-test --link --auto --batch siek-interpreter-test/

      - name: Run siek-interpreter tests
        run: raco test -c tests/siek-interpreter

      - name: Install siek-compiler-lib
        run: raco pkg install --name siek-compiler-lib --link --auto --batch siek-compiler-lib/

      - name: Install siek-compiler-test
        run: raco pkg install --name siek-compiler-test --link --auto --batch siek-compiler-test/

      - name: Run siek-compiler tests
        run: raco test -c tests/siek-compiler

      - name: Run siek-compiler-commutative tests
        run: raco test -c tests/siek-compiler-commutative
